name: 'build_mau'
version: '1.0.0'

profile: 'build_mau'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  build_mau:
    +materialized: table    # Default all models to table (recommended)
