version: 2

models:
  - name: stock_rsi
    description: "Calculates 14-day RSI for each stock symbol and date"
    columns:
      - name: SYMBOL
        description: "Stock symbol"
        tests:
          - not_null
      - name: DATE
        description: "Trade date"
        tests:
          - not_null
      - name: CLOSE
        description: "Closing price"
        tests:
          - not_null
      - name: rsi_14d
        description: "14-day Relative Strength Index"
        tests:
          - not_null

  - name: stock_moving_avg
    description: "Calculates 7-day moving average for each stock symbol and date"
    columns:
      - name: SYMBOL
        description: "Stock symbol"
        tests:
          - not_null
      - name: DATE
        description: "Trade date"
        tests:
          - not_null
      - name: CLOSE
        description: "Closing price"
        tests:
          - not_null
      - name: moving_avg_7d
        description: "7-day moving average of close price"
        tests:
          - not_null
